apiVersion: v1
data:
  password: dGVzdA==
kind: Secret
metadata:
  labels:
    app: notification-manager
  name: global-email-secret
  namespace: kubesphere-monitoring-system
type: Opaque
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: EmailConfig
metadata:
  labels:
    app: notification-manager
    type: tenant
    user: admin
  name: admin-email-config
  namespace: kubesphere-monitoring-system
spec:
  authPassword:
    key: password
    name: global-email-secret
    namespace: kubesphere-monitoring-system
  authUsername: abc1
  from: abc1@xyz.com
  requireTLS: true
  smartHost:
    host: imap.xyz.com
    port: "25"
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: EmailConfig
metadata:
  labels:
    app: notification-manager
    type: default
  name: default-email-config
  namespace: kubesphere-monitoring-system
spec:
  authPassword:
    key: password
    name: global-email-secret
    namespace: kubesphere-monitoring-system
  authUsername: abc999
  from: abc999@xyz.com
  requireTLS: true
  smartHost:
    host: imap.xyz.com
    port: "25"
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: EmailReceiver
metadata:
  labels:
    app: notification-manager
    type: tenant
    user: admin
  name: admin-email
  namespace: kubesphere-monitoring-system
spec:
  emailConfigSelector:
    matchLabels:
      type: tenant
      user: admin
  to:
  - abc2@xyz.com
  - abc3@xyz.com
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: EmailReceiver
metadata:
  labels:
    app: notification-manager
    type: global
  name: global-admin1-email
  namespace: kubesphere-monitoring-system
spec:
  emailConfigSelector:
    matchLabels:
      type: global
  to:
  - abc1@xyz.com
  - abc12@xyz.com
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: NotificationManager
metadata:
  labels:
    app: notification-manager
  name: notificationmanager-sample
  namespace: kubesphere-monitoring-system
spec:
  defaultConfigSelector:
    matchLabels:
      type: default
  image: kubesphere/notification-manager:latest
  imagePullPolicy: Always
  portName: webhook
  receivers:
    globalReceiverSelector:
      matchLabels:
        type: global
    options:
      email:
        deliveryType: bulk
        notificationTimeout: 5
      slack:
        notificationTimeout: 5
      wechat:
        notificationTimeout: 5
    tenantKey: user
    tenantReceiverSelector:
      matchLabels:
        type: tenant
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 20Mi
  serviceAccountName: notification-manager-sa
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: SlackConfig
metadata:
  labels:
    app: notification-manager
    type: default
  name: default-slack-config
  namespace: kubesphere-monitoring-system
spec:
  httpConfigSelector:
    matchLabels:
      type: tenant
      user: admin
  slackTokenSecret:
    key: token
    name: slack-token-secret
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: SlackReceiver
metadata:
  labels:
    app: notification-manager
    type: tenant
    user: admin
  name: admin-slack
  namespace: kubesphere-monitoring-system
spec:
  channel: slack_channel_x
  slackConfigSelector:
    matchLabels:
      type: tenant
      user: admin
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: WebhookConfig
metadata:
  labels:
    app: notification-manager
    type: default
  name: default-webhook-config
  namespace: kubesphere-monitoring-system
spec:
  httpConfigSelector:
    matchLabels:
      type: tenant
      user: admin
  url: xxx
  urlSecret:
    key: webhook-url
    name: webhook-url-secret
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: WebhookReceiver
metadata:
  labels:
    app: notification-manager
    type: tenant
    user: admin
  name: admin-webhook
  namespace: kubesphere-monitoring-system
spec:
  webhookConfigSelector:
    matchLabels:
      type: tenant
      user: admin
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: WechatConfig
metadata:
  labels:
    app: notification-manager
    type: default
  name: default-wechat-config
  namespace: kubesphere-monitoring-system
spec:
  wechatApiAgentId: wechat-api-agent-id
  wechatApiCorpId: wechat-api-corp-id
  wechatApiSecret:
    key: wechat
    name: wechat-api-secret
  wechatApiUrl: wechat-api-url
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: WechatReceiver
metadata:
  labels:
    app: notification-manager
    type: tenant
    user: admin
  name: admin-wechat
  namespace: kubesphere-monitoring-system
spec:
  toParty: wechat-party
  toTag: wechat-tag
  toUser: abc
  wechatConfigSelector:
    matchLabels:
      type: tenant
      user: admin
