apiVersion: notification.kubesphere.io/v1alpha1
kind: WebhookConfig
metadata:
  name: default-webhook-config
  labels:
    type: default
spec:
  url: xxx
  urlSecret:
    key: webhook-url
    name: webhook-url-secret
  httpConfigSelector:
    matchLabels:
      type: default
